name: Build wheel

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
    env:
      CIBW_SKIP: 'pp*'
      CIBW_ARCHS: 'auto64'
      CIBW_ARCHS_MACOS: "universal2"
      CIBW_PROJECT_REQUIRES_PYTHON: '>=3.11'
    defaults:
      run:
        shell: bash -l {0}
     
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4      

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Build Wheel
        run: |
          python -m pip install cibuildwheel==2.23.3
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
      - name: Run Example
        run: |
          export PATH="$pythonLocation:$PATH"
          python -m pip install numpy
          python -m pip install --no-index --find-links wheelhouse/ gimpact
          python -m unittest
